# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('wechat', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('fix_address', models.CharField(max_length=32)),
                ('fix_date', models.DateField()),
                ('apply_time', models.TimeField()),
                ('handled', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_address', models.CharField(max_length=128)),
                ('receipt_date', models.DateField()),
                ('order_time', models.TimeField()),
                ('payed', models.CharField(max_length=8)),
                ('order_index', models.CharField(max_length=64)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Agent')),
            ],
        ),
    ]
